# Generated by Django 5.2.17 on 2026-10-03 19:00

import django.db.models.deletion
import django.utils.timezone
import workforce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='America/Chicago', max_length=80)),
                ('briefing_time', models.TimeField(default='07:30')),
                ('pause_outbound', models.BooleanField(default=False)),
                ('pause_ai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('partner', 'Partner')], max_length=20)),
                ('pricing_approver', models.BooleanField(default=False)),
                ('notifications', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('shared', 'Shared household'), ('private', 'Only me')], default='private', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('provenance', models.CharField(choices=[('user_reported', 'User reported'), ('confirmed', 'User confirmed')], default='user_reported', max_length=20)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField(blank=True, max_length=10000)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('shared', 'Shared household'), ('private', 'Only me')], default='private', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('event', 'Event'), ('task', 'Task'), ('reminder', 'Reminder'), ('note', 'Note')], default='event', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('canceled', 'Canceled')], default='proposed', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Chicago', max_length=80, validators=[workforce.models.validate_zone])),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.sourcerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('shared', 'Shared household'), ('private', 'Only me')], default='private', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('booked', 'Bookings reported'), ('confirmed', 'Itinerary confirmed'), ('canceled', 'Canceled')], default='planning', max_length=20)),
                ('airport_buffer_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('ground_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('flight', 'Flight'), ('stay', 'Hotel stay')], max_length=10)),
                ('label', models.CharField(max_length=200)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Chicago', max_length=80, validators=[workforce.models.validate_zone])),
                ('arrival_timezone', models.CharField(default='America/Chicago', max_length=80, validators=[workforce.models.validate_zone])),
                ('verification', models.CharField(choices=[('user_reported', 'User reported'), ('confirmed', 'User confirmed')], default='user_reported', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='workforce.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('shared', 'Shared household'), ('private', 'Only me')], default='private', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('local_time', models.TimeField()),
                ('timezone', models.CharField(default='America/Chicago', max_length=80, validators=[workforce.models.validate_zone])),
                ('rule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('active_from', models.DateField(default=django.utils.timezone.localdate)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('audience__in', ['shared', 'private'])), name='routine_audience_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.CheckConstraint(condition=models.Q(('audience__in', ['shared', 'private'])), name='sourcerecord_audience_valid'),
        ),
        migrations.AddConstraint(
            model_name='planitem',
            constraint=models.CheckConstraint(condition=models.Q(('audience__in', ['shared', 'private'])), name='planitem_audience_valid'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('audience__in', ['shared', 'private'])), name='trip_audience_valid'),
        ),
    ]
