# Generated by Django 5.2.17 on 2026-10-03 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_household_invitation_membership_sourcerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=280, unique=True)),
                ('content', models.TextField()),
                ('refs', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previewed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_ref', models.CharField(blank=True, max_length=100)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.CharField(max_length=80)),
                ('kind', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=240, unique=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('lease_token', models.CharField(blank=True, max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
            ],
        ),
    ]
