# Generated by Django 5.2.17 on 2026-10-03 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_delivery_scheduledjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='briefing_time',
            field=models.TimeField(default=datetime.time(7, 30)),
        ),
    ]
