# Generated by Django 5.2.17 on 2026-10-03 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_alter_household_briefing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='auto_limit_cents',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.CreateModel(
            name='ActionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('shared', 'Shared household'), ('private', 'Only me')], default='private', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('workflow', models.CharField(choices=[('routine_appointment', 'Routine appointment'), ('household_task', 'Household task'), ('gift', 'Gift')], max_length=40)),
                ('vendor', models.CharField(max_length=200)),
                ('subtotal_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('fees_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('terms', models.TextField(blank=True, max_length=2000)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('availability_confirmed', models.BooleanField(default=False)),
                ('recurring', models.BooleanField(default=False)),
                ('quote_expires_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_group', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('ready_by', models.CharField(blank=True, max_length=20)),
                ('receipt', models.CharField(blank=True, max_length=200)),
                ('affected_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_actions', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(default='approved', max_length=10)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.actionproposal')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.CharField(max_length=80)),
                ('object_id', models.PositiveIntegerField()),
                ('event', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit_cents', models.PositiveIntegerField(default=30000)),
                ('variable_limit_cents', models.PositiveIntegerField(default=5000)),
                ('costs_confirmed', models.BooleanField(default=False)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('monthly_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='workforce.budgetconfig')),
            ],
        ),
        migrations.CreateModel(
            name='UsageReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('key', models.CharField(max_length=120, unique=True)),
                ('estimate_cents', models.PositiveIntegerField()),
                ('status', models.CharField(default='reserved', max_length=20)),
                ('actual_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.budgetconfig')),
            ],
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('estimated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workforce.usagereservation')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(max_length=40)),
                ('vendor', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.household')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='actionproposal',
            constraint=models.CheckConstraint(condition=models.Q(('audience__in', ['shared', 'private'])), name='actionproposal_audience_valid'),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(fields=('proposal', 'revision'), name='approval_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='workflowpolicy',
            constraint=models.UniqueConstraint(fields=('household', 'owner', 'workflow', 'vendor'), name='workflow_policy_unique'),
        ),
    ]
